### ISSUE TITLE
Import to update current dashboard

### ISSUE THREAD

**Issue by atbohmer** [StamusNetworks/KTS7#4]
Hello,
Already running an ELK setup with KTS7, but how to updates these dashboards? When running the curl import commands, it complains of conflicting indices. Logical because they already exist, but nothing is now imported. Removed kibana alias and indices and started a new import but to no avail.
Cheers,
Andre

**Comment by pevma** [comment]
You can then simply upload the same ndjson files from the Kibana web management interface or simply run a the `selks-upgrade_stamus` script after which you would need to reload the dashboards.

**Comment by atbohmer** [comment]
Running a custom setup on RedHat EL 7, so no Selks/stamus distro. But via Stack Management
Saved objects Import I was able to import the ndjson files and all dashboards seem to be back again.
Thanks!

**Comment by pevma** [comment]
Glad to hear it went ok!
