### ISSUE TITLE
Could not locate that index-pattern-field (id: http.accept_encoding.keyword)

### ISSUE THREAD

**Issue by alphaDev23** [StamusNetworks/KTS7#5]
Received 'Could not locate that index-pattern-field (id: http.accept_encoding.keyword)' in  the http dashboard.  The logstash-http-* index does not contain the field; it does contain 'http.accept' and 'http.accept_keyword' fields.  Setup is from suricata and filebeat on a router -> logstash -> elasticsearch.

While this may have been a previous issue, it did not come up when searching 'accept_encoding' in either this repo or the SELKS repo.

**Comment by pevma** [comment]
I can see two possibilities if i am not missing something.
Either there is data missing or maybe you are not running the latest vizs?  
I can see the dashboard populating ok here -   
![Screenshot from 2021-02-02 11-14-27](https://user-images.githubusercontent.com/1405917/106586586-f062f580-6548-11eb-9fb5-188eee6e5a3e.png)

**Comment by alphaDev23** [comment]
After update the to the latest, the issue is resolved.  Thank you for your help.
